import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { getMatch } from '../api/client';

export default function Commentary() {
    const { id } = useParams();
    const [match, setMatch] = useState<any>(null);

    useEffect(() => {
        getMatch(Number(id)).then(r => setMatch(r.data));
    }, [id]);

    if (!match) return <div className="page-container"><div className="spinner" style={{ margin: '80px auto' }} /></div>;

    return (
        <div className="page-container" style={{ maxWidth: '1000px', margin: '0 auto' }}>
            <h1 className="page-title">Match Commentary</h1>
            <p className="page-subtitle">AI-generated commentary combining expert analysis and match narration</p>

            <div className="glass-card" style={{ padding: '0', overflow: 'hidden', borderRadius: '16px' }}>
                {match.commentary_video_path ? (
                    <div>
                        <video
                            controls
                            style={{ width: '100%', borderRadius: '16px 16px 0 0', background: '#000' }}
                            poster=""
                        >
                            <source src={`/api/static/${match.commentary_video_path}`} type="video/mp4" />
                            Your browser does not support the video tag.
                        </video>
                        <div style={{ padding: '24px' }}>
                            <h3 style={{ fontWeight: 700, marginBottom: '8px' }}>
                                {match.home_team || 'Home'} vs {match.away_team || 'Away'}
                            </h3>
                            <p style={{ color: 'var(--text-secondary)' }}>
                                Full match commentary with AI-generated expert analysis and narration
                            </p>
                        </div>
                    </div>
                ) : (
                    <div style={{ textAlign: 'center', padding: '80px 40px' }}>
                        <div style={{ fontSize: '4rem', marginBottom: '16px' }}>🎙️</div>
                        <h3 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: '8px' }}>
                            Commentary Not Ready
                        </h3>
                        <p style={{ color: 'var(--text-secondary)', maxWidth: '400px', margin: '0 auto' }}>
                            {match.status === 'completed'
                                ? 'Commentary video is being processed by the commentary components. Check back soon.'
                                : `Match is still being processed (status: ${match.status}).`}
                        </p>
                    </div>
                )}
            </div>

            {/* Match Info */}
            <div className="glass-card" style={{ marginTop: '24px' }}>
                <h3 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '12px' }}>About This Commentary</h3>
                <p style={{ color: 'var(--text-secondary)', lineHeight: 1.8 }}>
                    This commentary is generated by combining two AI components:
                </p>
                <ul style={{ color: 'var(--text-secondary)', marginTop: '12px', paddingLeft: '20px', lineHeight: 2 }}>
                    <li><strong style={{ color: 'var(--text-primary)' }}>Expert Analysis Commentary</strong> — Uses match analytics (xG, xT, VAEP) to provide tactical insights</li>
                    <li><strong style={{ color: 'var(--text-primary)' }}>General Commentary</strong> — Play-by-play match narration</li>
                </ul>
                <p style={{ color: 'var(--text-secondary)', marginTop: '12px' }}>
                    Both are merged into a single cohesive commentary video.
                </p>
            </div>
        </div>
    );
}
